### PR TITLE
merged all three files in one

### PR DESCRIPTION
**Pull request by Suryansh470**
As discussed all the three files are now merged in one .

### CODE REVIEW

**Comment by ShikherVerma** [comment]
yo why not edit the wiki tab above ^. The repo was supposed be just a dummy. And a place to keep pdfs which can be linked to from the wiki.

**Comment by Suryansh470** [comment]
okay !!! 👍

**Comment by Suryansh470** [comment]
@ShikherVerma is it the case that only moderators can edit the wiki page???

**Comment by ShikherVerma** [comment]
Then make everyone moderator, or whenever access is required in the settings.

**Comment by Mayankm96** [comment]
@ShikherVerma  I haven't added made them moderators yet because then it is tough to keep a check on pull requests. Sab master pe hi commit karke push karte rahenge which I don't think we should have right now. 

Also I don't want docs to be submitted there without having been reviewed by us for maintaining a decent quality.

**Comment by Mayankm96** [comment]
@Suryansh470 I'll probably copy and paste the scripts to the wiki part. It's like a two minutes work if the docs are good. You don't need to worry about that. 

Just gonna see them once right now. Sorry for the delay!

**Pull request closed without merging**
