### PR TITLE
Documentation controls

### PR DESCRIPTION
**Pull request by Suryansh470**
see i have made a pull request again....

### CODE REVIEW

**Comment by Mayankm96** [comment]
You shouldn't keep doing this all the time. It just makes the repository messier :P 

Anyway I'll keep this open, till you add other documents now. We can probably try having a proper wiki-site instead of github wiki only. Suggestions @ShikherVerma

**Comment by ShikherVerma** [comment]
Well the people on campus should decide this :P its there project now.

**Comment by alicanuzun** [comment]
there is a problem in [this](https://github.com/AUV-IITK/AUVWiki/wiki/Installing-Gazebo7-with-ROS-Indigo) link. some of the packages not found.(404)

**Comment by Mayankm96** [comment]
@alicanuzun, could you please elucidate on which packages installation is throwing that error? 

Also I have enabled an [issues](https://github.com/AUV-IITK/AUVWiki/issues), it would be great if the issue could be posted there.

**Comment by Mayankm96** [comment]
@Suryansh470 I am closing this pull request since we have added the documentations on the wiki page.

**Pull request closed without merging**
